/***********************************************************************************************
 * Descripcion 		Clase HttpMock
 * Proyecto			CAPACITACION UAO
 * *********************************************************************************************/
@isTest
global class ServicioanimalesHttpcalloutMocktstnousar {
   /* global HTTPResponse respond(HTTPRequest request){
        HttpResponse response = new HttpResponse();
        response.setHeader('Content-Type', 'application/json');
        response.setBody('{"animals":["majestic badger","fluffy bunny","scary bear","chicken"]}');
        response.setStatusCode(200);
        return response;
    } */ 
}